FROM node:12-alpine
LABEL maintainer="Carlos Justiniano cjus@ieee.org"
EXPOSE 12000
RUN apk -U upgrade \
  && apk add --no-cache \
    curl \
    build-base
RUN mkdir -p /logs
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ADD . /usr/src/app
RUN npm install --production
CMD tail -f /dev/null
