FROM node:12-alpine
LABEL maintainer="Carlos Justiniano cjus@ieee.org"
EXPOSE 12000
RUN apk add --update \
    curl \
    python \
    build-base \
  && rm -rf /var/cache/apk/*
RUN mkdir -p /logs
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ADD . /usr/src/app
RUN npm install --production
CMD tail -f /dev/null
